DELIMITER //

CREATE EVENT IF NOT EXISTS NOMINA_TG
ON SCHEDULE EVERY 1 MONTH STARTS '2023-01-01 00:00:00'
DO
BEGIN
    UPDATE dev_testeos.bancoobrero
    SET CREDITOS = 
        CASE
            WHEN NIVEL = 'A' THEN CREDITOS + 1800
            WHEN NIVEL = 'B' THEN CREDITOS + 1400
            WHEN NIVEL = 'C' THEN CREDITOS + 1200
            ELSE CREDITOS
        END;
END //

DELIMITER ;
